FROM node:18 as build-stage

WORKDIR /app
COPY frontend/ /app

RUN npm install
RUN npm run build

FROM caddy:2.7.6-alpine

COPY --from=build-stage /app/dist /usr/share/caddy
COPY Caddyfile /etc/caddy/Caddyfile

EXPOSE 80