# Generated by Django 5.2.2 on 2025-06-04 22:03

import django.db.models.deletion
import sysdoc.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('inicio', models.DateTimeField(blank=True)),
                ('fim', models.DateTimeField(blank=True)),
                ('descricao', models.TextField(blank=True, max_length=200, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('pontos', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itemizacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, max_length=200, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('itemSuperior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='sysdoc.itemizacao')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysdoc.processo')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TarefaProcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('ponto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimo', models.IntegerField(blank=True)),
                ('maximo', models.IntegerField(blank=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='sysdoc.itemizacao')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysdoc.processo')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioProcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=45)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('log', models.TextField(blank=True, max_length=1000, null=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sysdoc.processo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioDocs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=sysdoc.models.upload_to_user_directory)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('descricao', models.TextField(blank=True, max_length=200, null=True)),
                ('quantidade', models.IntegerField(blank=True)),
                ('qdeReajustada', models.IntegerField(blank=True, null=True)),
                ('obsReajuste', models.TextField(blank=True, null=True)),
                ('tarefaProcesso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sysdoc.tarefaprocesso')),
                ('usuarioProcesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysdoc.usuarioprocesso')),
            ],
        ),
    ]
