# Generated by Django 5.2.1 on 2025-05-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysdoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefaprocesso',
            name='ponto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
