# Generated by Django 5.2.1 on 2025-05-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysdoc', '0002_alter_tarefaprocesso_ponto'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
